apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dawn-treader.fullname" . }}-config
  labels:
    {{- include "dawn-treader.labels" . | nindent 4 }}
data:
  node-env: "production"
  
  db-path: "/usr/src/app/db/mydatabase.db"
  
  redis-url: "redis://redis:6379"
  redis-host: "redis"
  redis-port: "6379"
  
  # Blockchain
  avalanche-rpc-url: "https://api.avax-test.network/ext/c/C/rpc"
   
  backend-url: "http://backend:3100"
  frontend-url: "http://frontend:5173"
  blockchain-url: "http://blockchain:3002"