- name: Import Docker images into k3d cluster
  shell: |
    k3d image import \
    app-frontend:latest \
    app-backend:latest \
    app-redis:latest \
    app-adminer:latest \
    app-blockchain:latest \
    app-prometheus:latest \
    app-grafana:latest \
    -c dawn-treader
