apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-userbase
  labels:
    {{- include "dawn-treader.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.storage.userbase.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-avatars
  labels:
    {{- include "dawn-treader.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared
spec:
  accessModes:
    - ReadWriteOnce  # temporary fix, change to ReadWriteMany when using a suitable storage class
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.storage.avatars.size }}
