apiVersion: v2
name: dawn-treader
description: Application Transcendence - Full Stack Web Application
type: application

version: 0.2.0
appVersion: "1.0.1"

maintainers:
  - name: Nicolas
    email: ponchon.nicolas@gmail.com