{{- if .Values.adminer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    {{- include "dawn-treader.labels" . | nindent 4 }}
    app.kubernetes.io/component: adminer
spec:
  type: {{ .Values.adminer.service.type }}
  ports:
  - port: {{ .Values.adminer.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: adminer
{{- end }}
